// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import context "context"

import infrastructures "github.com/HoaHuynhSoft/go-core/infrastructures"
import mock "github.com/stretchr/testify/mock"

// IHandler is an autogenerated mock type for the IHandler type
type IHandler struct {
	mock.Mock
}

// Handle provides a mock function with given fields: ctx, command
func (_m *IHandler) Handle(ctx context.Context, command interface{}) *infrastructures.Result {
	_m.On("Handle", ctx, command).Return(&infrastructures.Result{IsSuccess: true})
	ret := _m.Called(ctx, command)

	var r0 *infrastructures.Result
	if rf, ok := ret.Get(0).(func(context.Context, interface{}) *infrastructures.Result); ok {
		r0 = rf(ctx, command)
	} else {
		r0 = ret.Get(0).(*infrastructures.Result)
	}

	return r0
}
